### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by dra27**
I think may address the failure noted in https://github.com/mirage/mmap/pull/1#issuecomment-471974806

### CODE REVIEW

**Comment by ghost** [comment]
Indeed, it seems to be going further

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
I noticed this morning that there is a mmap.c file in otherlibs/win32unix. I think I forgot to copy this file in this repository, that might explain the failure

**Comment by dra27** [comment]
Yes, indeed - although really they want merging.

**Comment by dra27** [comment]
I'm a bit confused, though - why does this library vendor the C files at all?

**Comment by ghost** [comment]
Because these functions are not available with older OCaml versions. We could up the lower bound, but then the whole point of this package was to bring the new API to older compilers. Additionally, it will be much easier to make the api evolve in the future if this package is self contained.

**Comment by dra27** [comment]
Surely though if building on 4.06+ it doesn't want to be vendored, and you want to use the underlying one? Otherwise, if there's a fix, isn't there a confusing risk that this library unexpectedly causes a newer version of OCaml to use an older version's implementation?

**Comment by ghost** [comment]
@dra27, in your proposal, how do you deal with the following situation: `Unix.map_file` gets a new optional argument. The interpretation of this new optional argument requires changes to the C stubs. How do you backport the new functionality to older compilers?

**Pull request merged**
